import {mkdir,writeFile} from "node:fs/promises"
import path from "node:path"
import {test,expect} from "./demoman-test"
import {chooseTf2Team} from "./team-selection-evidence"
import {loadLocalConfig} from "../src/config"

test.use({video:{mode:"on",size:{width:1280,height:720}}})
test("stock Grenade Launcher arcs, bounces and detonates on its fuse",async({page,nativeGameplay},testInfo)=>{
  test.setTimeout(150_000)
  await page.addInitScript(()=>{(globalThis as any).__playsrcProfile={captureProjectileGameplay:true}})
  await page.goto("/")
  const root=page.locator("main")
  await page.waitForFunction(()=>["Startup","MainMenu","Failed"].includes(document.querySelector<HTMLElement>("main")?.dataset.phase??""))
  if(await root.getAttribute("data-phase")==="Startup")await page.keyboard.press("Escape")
  await expect(root).toHaveAttribute("data-phase","MainMenu",{timeout:30_000})
  const command=async(value:string)=>{
    if(await root.getAttribute("data-console-visible")!=="true")await page.keyboard.press("Backquote")
    const input=page.locator("[aria-label='Console command']");await expect(input).toBeVisible();await input.fill(value);await input.press("Enter")
    if(await root.getAttribute("data-console-visible")==="true")await page.keyboard.press("Backquote")
  }
  await command("map jump_beef")
  await page.waitForFunction(()=>{const d=document.querySelector<HTMLElement>("main")?.dataset;return d?.teamSelectionVisible==="true"||d?.phase==="Ready"||d?.phase==="Failed"},undefined,{timeout:90_000})
  if(await root.getAttribute("data-team-selection-visible")==="true")await chooseTf2Team(page,"red")
   await command("joinclass demoman")
   await expect(root).toHaveAttribute("data-phase","Ready",{timeout:30_000})
   await expect.poll(async()=>(await root.getAttribute("data-hud-probe"))?.split(":")[1]).toBe("4")
  await command("setpos 5328 3376 -3118")
  await expect.poll(async()=>Number((await page.evaluate(()=>(globalThis as any).__playsrcProfile.projectileState))?.position?.[0])).toBe(5328)
  const local=await loadLocalConfig()
  await page.keyboard.press("Digit1")
  await expect.poll(async()=>((await root.getAttribute("data-hud-probe"))??"").split(":")[2]).toBe("18")
   const canvas=page.locator("canvas.world-canvas")
    const pointer=await nativeGameplay.lockPointer()
  const selected=Number(await root.getAttribute("data-snapshot-tick"))
  await page.waitForFunction(tick=>Number(document.querySelector<HTMLElement>("main")?.dataset.snapshotTick)>tick+36,selected)
  const yaw=Number(await root.getAttribute("data-camera-yaw")),pitch=Number(await root.getAttribute("data-camera-pitch"))
  await page.mouse.move(pointer.x+(yaw-180)/0.066,pointer.y-pitch/0.066)
  await expect.poll(async()=>Math.abs(Number(await root.getAttribute("data-camera-yaw"))-180)).toBeLessThan(1)
  await expect.poll(async()=>Math.abs(Number(await root.getAttribute("data-camera-pitch")))).toBeLessThan(1)
  const directory=path.join(local.sourceCacheDir,"evidence","demoman-grenade",path.basename(process.env.PLAYSRC_PROFILE_RUN_DIRECTORY!));await mkdir(directory,{recursive:true})
  await canvas.screenshot({path:path.join(directory,"before.png")})
  const begin=Number(await root.getAttribute("data-snapshot-tick"));const started=Date.now()
  await page.evaluate(()=>{const profile=(globalThis as any).__playsrcProfile;profile.grenadeSamples=[];const end=performance.now()+5000;const capture=()=>{const state=profile.projectileState;if(state&&profile.grenadeSamples.at(-1)?.tick!==state.tick)profile.grenadeSamples.push(structuredClone(state));if(performance.now()<end)requestAnimationFrame(capture)};requestAnimationFrame(capture)})
  await page.mouse.down({button:"left"})
  await page.waitForFunction(tick=>Number(document.querySelector<HTMLElement>("main")?.dataset.snapshotTick)>tick+5,begin)
  await page.mouse.up({button:"left"})
   for(const [label,offset] of [["flight",12],["bounce",45]] as const){
     await page.waitForFunction(tick=>Number(document.querySelector<HTMLElement>("main")?.dataset.snapshotTick)>=tick,begin+offset)
     await nativeGameplay.capture(`grenade-${label}`)
    await canvas.screenshot({path:path.join(directory,`${label}.png`)})
  }
   await page.waitForFunction(()=>(globalThis as any).__playsrcProfile.projectileEvents?.some((event:any)=>event.type==="explode"&&event.kind===5),undefined,{timeout:5000})
   await nativeGameplay.capture("grenade-exploded")
  await canvas.screenshot({path:path.join(directory,"fuse-explosion.png")})
  const remaining=5000-(Date.now()-started)
  if(remaining>0)await page.waitForFunction(time=>performance.now()>=time,await page.evaluate(delay=>performance.now()+delay,remaining))
  const report=await page.evaluate(()=>({events:(globalThis as any).__playsrcProfile.projectileEvents,samples:(globalThis as any).__playsrcProfile.grenadeSamples}))
  const events=report.events.filter((event:any)=>event.kind===5),fire=events.find((event:any)=>event.type==="fire"),explosion=events.find((event:any)=>event.type==="explode")
  expect(fire).toBeDefined();expect(explosion).toBeDefined()
  expect((Number(explosion.tick)-Number(fire.tick))*0.015).toBeGreaterThan(2)
  expect(events.some((event:any)=>event.type==="impact")).toBe(true)
  expect(events.some((event:any)=>event.type==="stick")).toBe(false)
  const flying=report.samples.flatMap((sample:any)=>sample.projectileItems.filter((item:any)=>item.kind===5))
  expect(flying.some((item:any)=>item.velocity[2]>0)).toBe(true)
  expect(flying.some((item:any)=>item.velocity[2]<0)).toBe(true)
  await expect(root).toHaveAttribute("data-phase","Ready")
  await writeFile(path.join(directory,"report.json"),JSON.stringify(report,null,2)+"\n")
  await testInfo.attach("grenade-gameplay",{body:JSON.stringify(report),contentType:"application/json"})
})
