import path from "node:path"
import { pathToFileURL } from "node:url"
import { cp, mkdir, readFile, writeFile } from "node:fs/promises"
import { createHash } from "node:crypto"
import { readWasmManifest } from "../src/tf2-wasm-build"

/** Host loader only: generated WASM, glue and Rayon helpers remain byte-exact.
 * The metrics package resolves the same public clock import used by Vite. No
 * browser, display, collision selector or game-time substitute is created. */
export async function exactWasmReplayRuntime(source: string, output: string, threads: number) {
  if (!Number.isSafeInteger(threads) || threads < 1 || threads > 64) throw new Error("Invalid diagnostic thread count")
  const recorded = JSON.parse(await readFile(path.join(source, ".playsrc-build.json"), "utf8"))
  const manifest = await readWasmManifest(source, recorded.identity)
  if (!manifest) throw new Error("Recorded generated closure is unavailable or changed")
  const wasmIdentity = manifest.files.find(file => file.name === "tf2_wasm_bg.wasm")!
  const NativeWorker = globalThis.Worker, workers: Worker[] = []
  let closed = false
  globalThis.Worker = class extends NativeWorker {
    constructor(url: string | URL, options?: WorkerOptions) { super(url, options); workers.push(this) }
  } as typeof Worker
  return {
    manifest,
    async instantiate(bytes: Uint8Array, pass: number) {
      if (createHash("sha256").update(bytes).digest("hex") !== wasmIdentity.sha256) throw new Error("Binary does not match its exact producer closure")
      const directory = path.join(output, String(pass))
      await cp(source, directory, { recursive: true })
      const metrics = path.join(directory, "node_modules/playsrc_metrics")
      await mkdir(metrics, { recursive: true })
      await writeFile(path.join(directory, "package.json"), JSON.stringify({ type: "module" }))
      await writeFile(path.join(metrics, "package.json"), JSON.stringify({ name: "playsrc_metrics", type: "module", main: "index.js" }))
      await writeFile(path.join(metrics, "index.js"), "export function monotonic_milliseconds(){return performance.now()}\n")
      if (!await readWasmManifest(directory, manifest.identity)) throw new Error("Diagnostic loader changed generated bytes")
      const binding = await import(pathToFileURL(path.join(directory, "tf2_wasm.js")).href)
      const exports = binding.initSync({ module: bytes })
      await binding.initThreadPool(threads)
      return exports
    },
    async close() {
      if (closed) return
      closed = true
      await Promise.all(workers.map(worker => worker.terminate()))
      globalThis.Worker = NativeWorker
    },
  }
}
