import {
  DEFAULT_SETTINGS_LIMITS,
  SOURCE_CONVAR_FLAGS,
  SOURCE_KEY_MODIFIERS,
  defineSettingsCatalog,
  type BindingConflictPolicy,
  type OwnerAvailability,
  type SettingOwner,
  type SettingsCatalog,
} from "../src"

const ARCHIVE = SOURCE_CONVAR_FLAGS.ARCHIVE

export function fixtureCatalog(
  conflictPolicy: BindingConflictPolicy = "replace",
  limitOverrides: Partial<typeof DEFAULT_SETTINGS_LIMITS> = {},
): SettingsCatalog {
  return defineSettingsCatalog({
    identity: `test.settings.${conflictPolicy}`,
    limits: limitOverrides,
    convars: [
      { name: "volume", defaultValue: "1.0", help: "Master volume", flags: ARCHIVE, visibility: "visible", minimum: 0, maximum: 1 },
      { name: "mat_picmip", defaultValue: "0", help: "Texture detail", flags: ARCHIVE, visibility: "visible", minimum: -1, maximum: 4 },
      { name: "mat_vsync", defaultValue: "0", help: "Vertical synchronization", flags: ARCHIVE, visibility: "visible", minimum: 0, maximum: 1 },
      { name: "player_name", defaultValue: "Player", help: "Player name", flags: ARCHIVE, visibility: "visible" },
    ],
    commands: [
      { name: "bind", help: "Bind a key", flags: SOURCE_CONVAR_FLAGS.DO_NOT_RECORD, visibility: "visible", completion: "none" },
    ],
    bindingProfile: {
      identity: "test.desktop",
      inputs: [
        { code: "space", aliases: ["spacebar"] },
        { code: "key-k", aliases: ["k"] },
        { code: "key-m", aliases: ["m"] },
        { code: "escape", aliases: ["esc"] },
      ],
      modifierMask: SOURCE_KEY_MODIFIERS.ALL,
      conflictPolicy,
      reserved: [{ code: "escape", modifiers: SOURCE_KEY_MODIFIERS.NONE }],
    },
    settings: [
      {
        kind: "float",
        id: "audio.master-volume",
        page: "audio",
        owner: "audio",
        defaultValue: 1,
        minimum: 0,
        maximum: 1,
        flags: ARCHIVE,
        visibility: "visible",
        restart: "live",
        persistence: "persistent",
        consoleNames: ["volume"],
      },
      {
        kind: "boolean",
        id: "audio.master-muted",
        page: "audio",
        owner: "audio",
        defaultValue: false,
        flags: 0,
        visibility: "visible",
        restart: "live",
        persistence: "persistent",
        consoleNames: [],
      },
      {
        kind: "integer",
        id: "video.texture-detail",
        page: "video",
        owner: "renderer",
        defaultValue: 0,
        minimum: -1,
        maximum: 4,
        flags: ARCHIVE,
        visibility: "visible",
        restart: "owner-restart",
        persistence: "persistent",
        consoleNames: ["mat_picmip"],
      },
      {
        kind: "enum",
        id: "video.vsync",
        page: "video",
        owner: "renderer",
        defaultValue: 0,
        options: [
          { value: 0, label: "Disabled" },
          { value: 1, label: "Enabled" },
        ],
        flags: ARCHIVE,
        visibility: "visible",
        restart: "live",
        persistence: "persistent",
        consoleNames: ["mat_vsync"],
      },
      {
        kind: "string",
        id: "application.player-name",
        page: "multiplayer",
        owner: "application",
        defaultValue: "Player",
        minimumUtf8Bytes: 1,
        maximumUtf8Bytes: 12,
        flags: ARCHIVE,
        visibility: "visible",
        restart: "application-restart",
        persistence: "persistent",
        consoleNames: ["player_name"],
      },
      {
        kind: "binding",
        id: "input.jump",
        page: "keyboard",
        owner: "input",
        defaultValue: { code: "space", modifiers: 0 },
        action: "+jump",
        flags: SOURCE_CONVAR_FLAGS.DO_NOT_RECORD,
        visibility: "visible",
        restart: "live",
        persistence: "persistent",
        consoleNames: ["bind"],
      },
      {
        kind: "binding",
        id: "input.voice",
        page: "keyboard",
        owner: "input",
        defaultValue: { code: "key-k", modifiers: SOURCE_KEY_MODIFIERS.CONTROL },
        action: "+voicerecord",
        flags: SOURCE_CONVAR_FLAGS.DO_NOT_RECORD,
        visibility: "visible",
        restart: "live",
        persistence: "persistent",
        consoleNames: ["bind"],
      },
      {
        kind: "boolean",
        id: "session.preview",
        page: "video",
        owner: "renderer",
        defaultValue: false,
        flags: 0,
        visibility: "hidden",
        restart: "live",
        persistence: "session",
        consoleNames: [],
      },
    ],
  })
}

export function availableOwners(
  overrides: Partial<Record<SettingOwner, OwnerAvailability>> = {},
): Record<SettingOwner, OwnerAvailability> {
  return {
    renderer: "available",
    audio: "available",
    input: "available",
    game: "available",
    application: "available",
    ...overrides,
  }
}
