[workspace]
members = [
  "packages/formats/bsp/rust",
  "packages/formats/keyvalues/rust",
  "packages/formats/vpk/rust",
  "packages/formats/vmt/rust",
  "packages/formats/vtf/rust",
  "packages/formats/studio-model/rust",
  "packages/formats/phy/rust",
  "packages/content/rust",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
