import { headedProfileConfiguration } from "./tools/playsrc/profile/profile-config"
import { headedProfileTarget } from "./tools/playsrc/profile/profile-target"

export default headedProfileConfiguration({
  match: process.env.PROFILE_SKINNING_EQUIVALENCE === "1"
    ? "skinning-equivalence.profile.ts"
    : process.env.PROFILE_SCENARIOS === "deathnotice" ? "combat-lifecycle.profile.ts"
    : process.env.PROFILE_SCENARIOS === "browser-input" ? "browser-input.profile.ts"
    : process.env.PROFILE_SCENARIOS === "damage-indicator" ? "damage-indicator.profile.ts"
    : process.env.PROFILE_SCENARIOS === "setup-round" ? "setup-round.profile.ts"
    : process.env.PROFILE_SCENARIOS === "control-points" ? "control-points.profile.ts"
    : process.env.PROFILE_SCENARIOS === "koth" ? "koth.profile.ts"
    : process.env.PROFILE_SCENARIOS === "map-admission" ? "map-admission.profile.ts"
    : process.env.PROFILE_SCENARIOS === "soundscape-selection" ? "soundscape-selection.profile.ts"
    : process.env.PROFILE_SCENARIOS === "soundscape-water" ? "soundscape-water.profile.ts"
    : process.env.PROFILE_SCENARIOS === "macos-window-identity" ? "macos-window-identity.profile.ts"
    : process.env.PROFILE_SCENARIOS === "sprite-orientation" ? "sprite-orientation.profile.ts"
    : process.env.PROFILE_SCENARIOS === "smokestack" ? "smokestack.profile.ts"
    : process.env.PROFILE_SCENARIOS === "pixel-visibility" ? "pixel-visibility.profile.ts"
    : process.env.PROFILE_SCENARIOS === "burning-flames" ? "burning-flames.profile.ts"
    : process.env.PROFILE_SCENARIOS === "attack-defend" ? "attack-defend.profile.ts"
    : process.env.PROFILE_SCENARIOS === "spy-cloak" ? "spy-cloak.profile.ts"
    : process.env.PROFILE_SCENARIOS === "trigger-door"
    ? "trigger-door.profile.ts"
    : process.env.PROFILE_SCENARIOS === "sniper-scope"
    ? "sniper-scope.profile.ts"
    : process.env.PROFILE_SCENARIOS === "integrated-lifecycle"
    ? "integrated-lifecycle.profile.ts"
    : process.env.PROFILE_PYRO_AUDIO === "1"
    ? "pyro-audio-release.profile.ts"
    : process.env.PROFILE_SKY_COHERENCE === "1"
    ? "sky-coherence.profile.ts"
    : process.env.PROFILE_2FORT_MEMORY === "1"
    ? "ctf-2fort-performance.profile.ts"
    : process.env.PROFILE_COMBAT_IMPACTS === "1"
      ? "combat-impact.profile.ts"
    : process.env.PROFILE_UPWARD_OUTDOORS === "1"
    ? "upward-outdoor.profile.ts"
    : process.env.PROFILE_SCENARIOS === "upward-training-bots"
      ? "upward-training-bots.profile.ts"
    : process.env.PROFILE_SCENARIOS === "frame-budget"
      ? "all-maps-frame-budget.profile.ts"
    : process.env.PROFILE_SCENARIOS === "application-upgrade"
      ? "application-upgrade.profile.ts"
    : process.env.PROFILE_SCENARIOS === "main-menu"
      ? "main-menu-inventory.profile.ts"
      : process.env.PROFILE_2FORT_VISUAL === "1"
        ? "ctf-2fort-visual.profile.ts"
        : process.env.PROFILE_SCENARIOS === "hud-layout"
          ? "hud-layout.profile.ts"
          : process.env.PROFILE_SCENARIOS === "2fort-match"
            ? "ctf-2fort-match.profile.ts"
            : process.env.PROFILE_SCENARIOS === "local-practice"
              ? "local-practice-match.profile.ts"
      : process.env.PROFILE_SCENARIOS === "upward-floor"
        ? "upward-outdoor-floor.profile.ts"
        : process.env.PROFILE_SCENARIOS === "scoreboard"
          ? "scoreboard-hud.profile.ts"
          : process.env.PROFILE_PICKUPS === "1"
            ? "pickup-resupply.profile.ts"
            : process.env.PROFILE_ROUND_RULES === "1"
              ? "round-rules.profile.ts"
              : process.env.PROFILE_CTF_BOTS === "1"
                ? "ctf-2fort-bots.profile.ts"
                : process.env.PROFILE_CTF_OBJECTIVES === "1"
                  ? "ctf-objectives.profile.ts"
                  : process.env.PROFILE_MATERIAL_ANIMATION === "1"
                    ? "material-animation.profile.ts"
                    : process.env.PROFILE_PYRO_STOCK === "1"
                      ? "pyro-stock.profile.ts"
                      : process.env.PROFILE_SCENARIOS === "demoman"
                        ? "demoman-bottle.profile.ts"
                        : process.env.PROFILE_MEDIC_WEAPONS === "1"
                          ? "medic-stock-weapons.profile.ts"
                          : process.env.PROFILE_TRACKTRAIN === "1"
                            ? "tracktrain.profile.ts"
                          : "input-latency.profile.ts",
  target: headedProfileTarget(),
  ...(process.env.PROFILE_SCENARIOS === "browser-input" && process.platform === "win32" ? { channel: "msedge" as const } : {}),
  ...(process.env.PROFILE_SCENARIOS === "team-selection" ? { grep: /profile startup and input latency/u } : {}),
})
