import { headedProfileConfiguration } from "./tools/playsrc/profile/profile-config"
import { headedProfileTarget } from "./tools/playsrc/profile/profile-target"

export default headedProfileConfiguration({
  match: process.env.PROFILE_COMBAT_IMPACTS === "1"
    ? "combat-impact.profile.ts"
    : process.env.PROFILE_UPWARD_OUTDOORS === "1"
    ? "upward-outdoor.profile.ts"
    : process.env.PROFILE_SCENARIOS === "main-menu"
      ? "main-menu-inventory.profile.ts"
    : process.env.PROFILE_SCENARIOS === "local-practice"
      ? "local-practice-match.profile.ts"
      : process.env.PROFILE_SCENARIOS === "upward-floor"
        ? "upward-outdoor-floor.profile.ts"
        : process.env.PROFILE_SCENARIOS === "scoreboard"
          ? "scoreboard-hud.profile.ts"
          : process.env.PROFILE_PICKUPS === "1"
            ? "pickup-resupply.profile.ts"
            : process.env.PROFILE_ROUND_RULES === "1"
              ? "round-rules.profile.ts"
              : process.env.PROFILE_CTF_BOTS === "1"
                ? "ctf-2fort-bots.profile.ts"
                : process.env.PROFILE_CTF_OBJECTIVES === "1"
                  ? "ctf-objectives.profile.ts"
                  : process.env.PROFILE_MATERIAL_ANIMATION === "1"
                    ? "material-animation.profile.ts"
                    : process.env.PROFILE_PYRO_STOCK === "1"
                      ? "pyro-stock.profile.ts"
                      : process.env.PROFILE_SCENARIOS === "demoman"
                        ? "demoman-bottle.profile.ts"
                        : process.env.PROFILE_MEDIC_WEAPONS === "1"
                          ? "medic-stock-weapons.profile.ts"
                          : process.env.PROFILE_TRACKTRAIN === "1"
                            ? "tracktrain.profile.ts"
                          : "input-latency.profile.ts",
  target: headedProfileTarget(),
  ...(process.env.PROFILE_SCENARIOS === "team-selection" ? { grep: /profile startup and input latency/u } : {}),
})
