[package]
name = "playsrc-tf2-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
playsrc-asset-graph = { path = "../../../packages/asset-store/rust" }
playsrc-bsp = { path = "../../../packages/formats/bsp/rust" }
playsrc-map = { path = "../../../packages/world/map/rust" }
playsrc-tf2 = { path = "../rust" }
playsrc-movement = { path = "../../../packages/runtime/movement/rust" }
playsrc-collision = { path = "../../../packages/world/collision/rust" }
playsrc-entity = { path = "../../../packages/world/entity/rust" }
playsrc-keyvalues = { path = "../../../packages/formats/keyvalues/rust" }
playsrc-material = { path = "../../../packages/world/material/rust" }
playsrc-particle = { path = "../../../packages/presentation/particle/rust" }
playsrc-simulation = { path = "../../../packages/runtime/simulation/rust" }
playsrc-phy = { path = "../../../packages/formats/phy/rust" }
playsrc-studio-model = { path = "../../../packages/formats/studio-model/rust" }
playsrc-vmt = { path = "../../../packages/formats/vmt/rust" }
playsrc-vtf = { path = "../../../packages/formats/vtf/rust" }
playsrc-visibility = { path = "../../../packages/world/visibility/rust" }
sha2 = "0.10.9"
