// Generated from configured items_game SHA-256 4d1f15b63e63e3e897552cfb8042cccb99d2e233a0c8d8afd8734a3ea49d08da.
// Regenerate with generate:tf2-ui.
pub const ITEM_PRESENTATIONS: &[ItemPresentation] = &[
ItemPresentation { definition_index: 0, name: "#TF_Weapon_Bat", image: "backpack/weapons/c_models/c_bat", class_slots: &[(PlayerClass::Scout, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 1, name: "#TF_Weapon_Bottle", image: "backpack/weapons/w_models/w_bottle", class_slots: &[(PlayerClass::Demoman, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 2, name: "#TF_Weapon_FireAxe", image: "backpack/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro", class_slots: &[(PlayerClass::Pyro, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 3, name: "#TF_Weapon_Club", image: "backpack/weapons/w_models/w_machete", class_slots: &[(PlayerClass::Sniper, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 4, name: "#TF_Weapon_Knife", image: "backpack/weapons/w_models/w_knife", class_slots: &[(PlayerClass::Spy, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 5, name: "#TF_Weapon_Fists", image: "backpack/weapons/v_models/v_fist_heavy", class_slots: &[(PlayerClass::Heavy, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 6, name: "#TF_Weapon_Shovel", image: "backpack/weapons/w_models/w_shovel", class_slots: &[(PlayerClass::Soldier, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 7, name: "#TF_Weapon_Wrench", image: "backpack/weapons/w_models/w_wrench", class_slots: &[(PlayerClass::Engineer, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 8, name: "#TF_Weapon_Bonesaw", image: "backpack/weapons/c_models/c_bonesaw/c_bonesaw", class_slots: &[(PlayerClass::Medic, LoadoutPosition::Melee)] },
ItemPresentation { definition_index: 9, name: "#TF_Weapon_Shotgun", image: "backpack/weapons/w_models/w_shotgun", class_slots: &[(PlayerClass::Engineer, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 10, name: "#TF_Weapon_Shotgun", image: "backpack/weapons/w_models/w_shotgun", class_slots: &[(PlayerClass::Soldier, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 11, name: "#TF_Weapon_Shotgun", image: "backpack/weapons/w_models/w_shotgun", class_slots: &[(PlayerClass::Heavy, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 12, name: "#TF_Weapon_Shotgun", image: "backpack/weapons/w_models/w_shotgun", class_slots: &[(PlayerClass::Pyro, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 13, name: "#TF_Weapon_Scattergun", image: "backpack/weapons/c_models/c_scattergun", class_slots: &[(PlayerClass::Scout, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 14, name: "#TF_Weapon_SniperRifle", image: "backpack/weapons/w_models/w_sniperrifle", class_slots: &[(PlayerClass::Sniper, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 15, name: "#TF_Weapon_Minigun", image: "backpack/weapons/w_models/w_minigun", class_slots: &[(PlayerClass::Heavy, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 16, name: "#TF_Weapon_SMG", image: "backpack/weapons/w_models/w_smg", class_slots: &[(PlayerClass::Sniper, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 17, name: "#TF_Weapon_SyringeGun", image: "backpack/weapons/w_models/w_syringegun", class_slots: &[(PlayerClass::Medic, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 18, name: "#TF_Weapon_RocketLauncher", image: "backpack/weapons/w_models/w_rocketlauncher", class_slots: &[(PlayerClass::Soldier, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 19, name: "#TF_Weapon_GrenadeLauncher", image: "backpack/weapons/w_models/w_grenadelauncher", class_slots: &[(PlayerClass::Demoman, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 20, name: "#TF_Weapon_PipebombLauncher", image: "backpack/weapons/w_models/w_stickybomb_launcher", class_slots: &[(PlayerClass::Demoman, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 21, name: "#TF_Weapon_FlameThrower", image: "backpack/weapons/c_models/c_flamethrower/c_flamethrower", class_slots: &[(PlayerClass::Pyro, LoadoutPosition::Primary)] },
ItemPresentation { definition_index: 22, name: "#TF_Weapon_Pistol", image: "backpack/weapons/c_models/c_pistol", class_slots: &[(PlayerClass::Scout, LoadoutPosition::Secondary), (PlayerClass::Engineer, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 23, name: "#TF_Weapon_Pistol", image: "backpack/weapons/c_models/c_pistol", class_slots: &[(PlayerClass::Scout, LoadoutPosition::Secondary), (PlayerClass::Engineer, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 24, name: "#TF_Weapon_Revolver", image: "backpack/weapons/w_models/w_revolver", class_slots: &[(PlayerClass::Spy, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 25, name: "#TF_Weapon_PDA_Engineer_Builder", image: "backpack/weapons/w_models/w_builder", class_slots: &[(PlayerClass::Engineer, LoadoutPosition::Pda)] },
ItemPresentation { definition_index: 26, name: "#TF_Weapon_PDA_Engineer_Destroyer", image: "backpack/weapons/w_models/w_pda_engineer", class_slots: &[(PlayerClass::Engineer, LoadoutPosition::Pda2)] },
ItemPresentation { definition_index: 27, name: "#TF_Weapon_Disguise_Kit", image: "backpack/weapons/w_models/w_cigarette_case", class_slots: &[(PlayerClass::Spy, LoadoutPosition::Pda)] },
ItemPresentation { definition_index: 28, name: "#TF_Weapon_PDA_Engineer", image: "backpack/weapons/w_models/w_pda_engineer", class_slots: &[(PlayerClass::Engineer, LoadoutPosition::Building)] },
ItemPresentation { definition_index: 29, name: "#TF_Weapon_Medigun", image: "backpack/weapons/c_models/c_medigun/c_medigun", class_slots: &[(PlayerClass::Medic, LoadoutPosition::Secondary)] },
ItemPresentation { definition_index: 30, name: "#TF_Weapon_Watch", image: "backpack/weapons/c_models/c_spy_watch/parts/c_spy_watch", class_slots: &[(PlayerClass::Spy, LoadoutPosition::Pda2)] },
ItemPresentation { definition_index: 735, name: "#TF_Weapon_Spy_Sapper", image: "backpack/weapons/w_models/w_sapper", class_slots: &[(PlayerClass::Spy, LoadoutPosition::Building)] },
];
fn configured_schema_input() -> crate::schema::SchemaInput {
use crate::schema::{SchemaInput, SchemaNode};
SchemaInput {
content_build: 24245096, schema_sha256: "4d1f15b63e63e3e897552cfb8042cccb99d2e233a0c8d8afd8734a3ea49d08da".into(), signature_sha256: "353a124196f1218738b2d2d1982052b3900d71c8afac4428f35c13aaf5dbbccb".into(),
game_info: vec![SchemaNode::scalar("first_valid_class", "1"),
SchemaNode::scalar("last_valid_class", "9"),
SchemaNode::scalar("account_class_index", "16"),
SchemaNode::scalar("account_first_valid_item_slot", "0"),
SchemaNode::scalar("account_last_valid_item_slot", "3"),
SchemaNode::scalar("first_valid_item_slot", "0"),
SchemaNode::scalar("last_valid_item_slot", "18"),
SchemaNode::scalar("num_item_presets", "4")],
prefabs: vec![SchemaNode::object("weapon_baseflamethrower", vec![SchemaNode::scalar("item_class", "tf_weapon_flamethrower"),
SchemaNode::scalar("prefab", "weapon_newflame"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_FlameThrower"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("pyro", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("extinguish restores health", "20")]),
SchemaNode::object("visuals", vec![SchemaNode::object("animation_replacement", vec![SchemaNode::scalar("ACT_MP_ATTACK_CROUCH_SECONDARYFIRE", "ACT_MP_ATTACK_CROUCH_PRIMARY_ALT"),
SchemaNode::scalar("ACT_MP_ATTACK_STAND_SECONDARYFIRE", "ACT_MP_ATTACK_STAND_PRIMARY_ALT"),
SchemaNode::scalar("ACT_MP_ATTACK_SWIM_SECONDARYFIRE", "ACT_MP_ATTACK_SWIM_PRIMARY_ALT")])])]),
SchemaNode::object("weapon_newflame", vec![SchemaNode::object("static_attrs", vec![SchemaNode::scalar("flame_gravity", "0"),
SchemaNode::scalar("flame_drag", "8.5"),
SchemaNode::scalar("flame_up_speed", "50"),
SchemaNode::scalar("flame_speed", "2450"),
SchemaNode::scalar("flame_spread_degree", "2.8"),
SchemaNode::scalar("flame_lifetime", "0.6"),
SchemaNode::scalar("flame_random_life_time_offset", "0.1")])]),
SchemaNode::object("weapon_bat", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_BAT"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_bat"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Bat"),
SchemaNode::scalar("item_name", "#TF_Weapon_Bat"),
SchemaNode::scalar("inspect_panel_dist", "35"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_bat"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("inspect_panel_dist", "45"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_bat.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("scout", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -7")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav")]),
SchemaNode::object("weapon_bonesaw", vec![SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_bonesaw"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_BONESAW"),
SchemaNode::scalar("show_in_armory", "1"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Bonesaw"),
SchemaNode::scalar("item_name", "#TF_Weapon_Bonesaw"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "unique"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "99"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_bonesaw/c_bonesaw"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("inspect_panel_dist", "42"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_bonesaw/c_bonesaw.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("medic", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -12")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav"),
SchemaNode::scalar("xifier_class_remap", "weapon_bonesaw")]),
SchemaNode::object("weapon_bottle", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_be_festivized", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_bottle"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Bottle"),
SchemaNode::scalar("item_name", "#TF_Weapon_Bottle"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_bottle"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("inspect_panel_dist", "30"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_bottle/c_bottle.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("demoman", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -14")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_bottle_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_bottle_drop.wav"),
SchemaNode::object("visuals", vec![SchemaNode::object("attached_models_festive", vec![SchemaNode::object("0", vec![SchemaNode::scalar("model", "models/weapons/c_models/c_bottle/c_bottle_festivizer.mdl")])])])]),
SchemaNode::object("weapon_club", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_club"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Club"),
SchemaNode::scalar("item_name", "#TF_Weapon_Club"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_machete"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_machete/c_machete.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("sniper", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -6")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_knife_small_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav")]),
SchemaNode::object("weapon_fireaxe", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_fireaxe"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_FireAxe"),
SchemaNode::scalar("item_name", "#TF_Weapon_FireAxe"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_fireaxe_pyro/c_fireaxe_pyro.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("pyro", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -9")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav")]),
SchemaNode::object("weapon_fists", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_fists"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Fists"),
SchemaNode::scalar("item_name", "#TF_Weapon_Fists"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/v_models/v_fist_heavy"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", ""),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("heavy", "1")]),
SchemaNode::object("visuals", vec![SchemaNode::object("animation_replacement", vec![SchemaNode::scalar("ACT_VM_IDLE", "ACT_FISTS_VM_IDLE"),
SchemaNode::scalar("ACT_VM_HITLEFT", "ACT_FISTS_VM_HITLEFT"),
SchemaNode::scalar("ACT_VM_HITRIGHT", "ACT_FISTS_VM_HITRIGHT"),
SchemaNode::scalar("ACT_VM_SWINGHARD", "ACT_FISTS_VM_SWINGHARD"),
SchemaNode::scalar("ACT_VM_DRAW", "ACT_FISTS_VM_DRAW")]),
SchemaNode::object("styles", vec![SchemaNode::object("0", vec![SchemaNode::scalar("skin_red", "2"),
SchemaNode::scalar("skin_blu", "3"),
SchemaNode::scalar("v_skin_red", "2"),
SchemaNode::scalar("v_skin_blu", "3"),
SchemaNode::scalar("selectable", "0")])])]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -7")])]),
SchemaNode::object("weapon_flamethrower", vec![SchemaNode::scalar("prefab", "weapon_baseflamethrower"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_reflect_projectiles", "1"),
SchemaNode::scalar("can_extinguish", "1"),
SchemaNode::scalar("can_deal_posthumous_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("is_flamethrower", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_FLAMETHROWER"),
SchemaNode::scalar("inspect_panel_dist", "91"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_name", "#TF_Weapon_FlameThrower"),
SchemaNode::scalar("item_description", "#TF_Weapon_FlameThrower_desc"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_flamethrower/c_flamethrower"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_flamethrower/c_flamethrower.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "1"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "flamethrower")]),
SchemaNode::object("weapon_grenade_launcher", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_gib_damage", "1"),
SchemaNode::scalar("can_deal_posthumous_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1"),
SchemaNode::scalar("can_be_equipped_by_soldier_or_demo", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_GRENADELAUNCHER"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_grenadelauncher"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_GrenadeLauncher"),
SchemaNode::scalar("item_name", "#TF_Weapon_GrenadeLauncher"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::scalar("anim_slot", "secondary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_grenadelauncher"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_grenadelauncher/c_grenadelauncher.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "55"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("demoman", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "1"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "grenade_launcher")]),
SchemaNode::object("weapon_invis", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_invis"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Watch"),
SchemaNode::scalar("item_name", "#TF_Weapon_Watch"),
SchemaNode::scalar("item_description", "#TF_Weapon_Watch_desc"),
SchemaNode::scalar("item_slot", "pda2"),
SchemaNode::scalar("anim_slot", "FORCE_NOT_USED"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_spy_watch/parts/c_spy_watch"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/v_models/v_watch_spy.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("spy", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "8 0 -6")]),
SchemaNode::object("attributes", vec![SchemaNode::object("kill eater score type", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type"),
SchemaNode::scalar("value", "58")])]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_watch_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_watch_drop.wav")]),
SchemaNode::object("weapon_knife", vec![SchemaNode::scalar("inspect_panel_dist", "25"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_taunt_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_KNIFE"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_knife"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Knife"),
SchemaNode::scalar("item_name", "#TF_Weapon_Knife"),
SchemaNode::scalar("item_description", "#TF_Weapon_Knife_desc"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_knife"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_knife/c_knife.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("spy", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.455"),
SchemaNode::scalar("min_viewmodel_offset", "5 0 -4")]),
SchemaNode::object("visuals", vec![SchemaNode::object("animation_replacement", vec![SchemaNode::scalar("ACT_VM_HITCENTER", "ACT_MELEE_VM_HITCENTER"),
SchemaNode::scalar("ACT_VM_SWINGHARD", "ACT_MELEE_VM_SWINGHARD")])]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_knife_small_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav"),
SchemaNode::scalar("particle_suffix", "knife")]),
SchemaNode::object("weapon_medigun", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_heal_allies", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_MEDIGUN"),
SchemaNode::scalar("inspect_panel_dist", "70"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_medigun"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Medigun"),
SchemaNode::scalar("item_name", "#TF_Weapon_Medigun"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("equip_region", "medigun_backpack"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_medigun/c_medigun"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_medigun/c_medigun.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("medic", "1")]),
SchemaNode::object("attributes", vec![SchemaNode::object("kill eater score type", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type"),
SchemaNode::scalar("value", "1")]),
SchemaNode::object("kill eater score type 2", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type_2"),
SchemaNode::scalar("value", "2")])]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "1"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -9")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "medigun")]),
SchemaNode::object("weapon_minigun", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_MINIGUN"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_minigun"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Minigun"),
SchemaNode::scalar("item_name", "#TF_Weapon_Minigun"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_minigun"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_minigun/c_minigun.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "88"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("heavy", "1")]),
SchemaNode::object("visuals_mvm_boss", vec![SchemaNode::scalar("sound_double_shot", "MVM.GiantHeavyGunFire"),
SchemaNode::scalar("sound_burst", "MVM.GiantHeavyGunFire"),
SchemaNode::scalar("sound_special1", "MVM.GiantHeavyGunWindUp"),
SchemaNode::scalar("sound_special2", "MVM.GiantHeavyGunWindDown"),
SchemaNode::scalar("sound_special3", "MVM.GiantHeavyGunSpin")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "1"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -9")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "minigun")]),
SchemaNode::object("weapon_pistol", vec![SchemaNode::scalar("craft_class", ""),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_pistol"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_PISTOL"),
SchemaNode::scalar("show_in_armory", "1"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Pistol"),
SchemaNode::scalar("item_name", "#TF_Weapon_Pistol"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "unique"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "31"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_pistol"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_pistol/c_pistol.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1"),
SchemaNode::scalar("scout", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.723"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "pistol")]),
SchemaNode::object("weapon_revolver", vec![SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_revolver"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_REVOLVER"),
SchemaNode::scalar("show_in_armory", "1"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Revolver"),
SchemaNode::scalar("item_name", "#TF_Weapon_Revolver"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "unique"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "99"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_revolver"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_revolver/c_revolver.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "31"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("spy", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.497"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -6")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav"),
SchemaNode::scalar("xifier_class_remap", "weapon_revolver"),
SchemaNode::scalar("particle_suffix", "revolver")]),
SchemaNode::object("weapon_rocketlauncher", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_gib_damage", "1"),
SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_be_equipped_by_soldier_or_demo", "1"),
SchemaNode::scalar("can_deal_posthumous_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_ROCKETLAUNCHER"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_rocketlauncher"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_RocketLauncher"),
SchemaNode::scalar("item_name", "#TF_Weapon_RocketLauncher"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_rocketlauncher"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "68"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_rocketlauncher/c_rocketlauncher.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("soldier", "1")]),
SchemaNode::object("visuals_mvm_boss", vec![SchemaNode::scalar("sound_single_shot", "MVM.GiantSoldierRocketShoot"),
SchemaNode::scalar("sound_burst", "MVM.GiantSoldierRocketShootCrit"),
SchemaNode::scalar("sound_special1", "MVM.GiantSoldierRocketExplode")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "1"),
SchemaNode::scalar("min_viewmodel_offset", "10 -3 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "rocketlauncher")]),
SchemaNode::object("weapon_sapper", vec![SchemaNode::scalar("enabled", "1"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_BUILDER_SPY"),
SchemaNode::scalar("item_class", "tf_weapon_builder"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_name", "#TF_Weapon_Spy_Sapper"),
SchemaNode::scalar("item_description", "#TF_Weapon_Spy_Sapper_desc"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Spy_Sapper"),
SchemaNode::scalar("item_slot", "building"),
SchemaNode::scalar("item_quality", "unique"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_sapper"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("inspect_panel_dist", "25"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_sapper/c_sapper.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("spy", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "5 -2 -4")]),
SchemaNode::object("attributes", vec![SchemaNode::object("kill eater score type", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type"),
SchemaNode::scalar("value", "24")])]),
SchemaNode::scalar("xifier_class_remap", "sapper"),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav")]),
SchemaNode::object("weapon_scattergun", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_SCATTERGUN"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_scattergun"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Scattergun"),
SchemaNode::scalar("item_name", "#TF_Weapon_Scattergun"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_scattergun"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "35"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_scattergun.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("scout", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.608"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -11")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "scattergun")]),
SchemaNode::object("weapon_shotgun", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_SHOTGUN_PRIMARY"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_shotgun"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Shotgun"),
SchemaNode::scalar("item_name", "#TF_Weapon_Shotgun"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("inspect_panel_dist", "40"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_shotgun"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_shotgun/c_shotgun.mdl"),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "shotgun"),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -9")])]),
SchemaNode::object("weapon_shovel", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_shovel"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Shovel"),
SchemaNode::scalar("item_name", "#TF_Weapon_Shovel"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_shovel"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("inspect_panel_dist", "45"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_shovel/c_shovel.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("soldier", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 -6 -12")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_shovel_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_shovel_drop.wav")]),
SchemaNode::object("weapon_smg", vec![SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_smg"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_SMG"),
SchemaNode::scalar("inspect_panel_dist", "39"),
SchemaNode::scalar("show_in_armory", "1"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_SMG"),
SchemaNode::scalar("item_name", "#TF_Weapon_SMG"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "unique"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_smg"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_smg/c_smg.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("sniper", "1")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav"),
SchemaNode::object("visuals", vec![SchemaNode::object("styles", vec![SchemaNode::object("0", vec![SchemaNode::scalar("skin_red", "0"),
SchemaNode::scalar("skin_blu", "1"),
SchemaNode::scalar("selectable", "0")]),
SchemaNode::object("1", vec![SchemaNode::scalar("skin_red", "2"),
SchemaNode::scalar("skin_blu", "3"),
SchemaNode::scalar("selectable", "0"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_smg/c_smg_gold")])])]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.505"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -7")]),
SchemaNode::scalar("xifier_class_remap", "weapon_smg"),
SchemaNode::scalar("particle_suffix", "smg")]),
SchemaNode::object("weapon_sniperrifle", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_headshot", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_SNIPERRIFLE"),
SchemaNode::scalar("inspect_panel_dist", "71"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_sniperrifle"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_SniperRifle"),
SchemaNode::scalar("item_name", "#TF_Weapon_SniperRifle"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_sniperrifle"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_sniperrifle/c_sniperrifle.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("sniper", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.676"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "sniperrifle")]),
SchemaNode::object("weapon_stickybomb_launcher", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_gib_damage", "1"),
SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_be_equipped_by_soldier_or_demo", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("base_item_name", "TF_WEAPON_PIPEBOMBLAUNCHER"),
SchemaNode::scalar("enabled", "1"),
SchemaNode::scalar("item_class", "tf_weapon_pipebomblauncher"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_PipebombLauncher"),
SchemaNode::scalar("item_name", "#TF_Weapon_PipebombLauncher"),
SchemaNode::scalar("item_description", "#TF_Weapon_PipebombLauncher_desc"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("anim_slot", "primary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_stickybomb_launcher"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_stickybomb_launcher/c_stickybomb_launcher.mdl"),
SchemaNode::scalar("inspect_panel_dist", "50"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("demoman", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.9"),
SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_heavy_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_heavy_gun_drop.wav"),
SchemaNode::scalar("particle_suffix", "stickybomb_launcher")]),
SchemaNode::object("weapon_syringegun", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_posthumous_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_syringegun_medic"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_SyringeGun"),
SchemaNode::scalar("item_name", "#TF_Weapon_SyringeGun"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_syringegun"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("inspect_panel_dist", "44"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_syringegun/c_syringegun.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("medic", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -12")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav")]),
SchemaNode::object("weapon_wrench", vec![SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_critical_damage", "1"),
SchemaNode::scalar("can_destroy_sappers", "1")]),
SchemaNode::scalar("inspect_panel_dist", "45"),
SchemaNode::scalar("base_item_name", "TF_WEAPON_WRENCH"),
SchemaNode::scalar("enabled", "0"),
SchemaNode::scalar("item_class", "tf_weapon_wrench"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Wrench"),
SchemaNode::scalar("item_name", "#TF_Weapon_Wrench"),
SchemaNode::scalar("item_description", "#TF_Weapon_Wrench_Desc"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "0"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_wrench"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_wrench/c_wrench.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("weapon_stattrak_module_scale", "0.756"),
SchemaNode::scalar("min_viewmodel_offset", "10 -2 -9")]),
SchemaNode::object("attributes", vec![SchemaNode::object("kill eater score type", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type"),
SchemaNode::scalar("value", "3")]),
SchemaNode::object("kill eater score type 2", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type_2"),
SchemaNode::scalar("value", "0")])]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav"),
SchemaNode::scalar("particle_suffix", "wrench")])],
attributes: vec![SchemaNode::object("292", vec![SchemaNode::scalar("name", "kill eater score type"),
SchemaNode::scalar("attribute_class", "kill_eater_score_type"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("effect_type", "positive"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("293", vec![SchemaNode::scalar("name", "kill eater score type 2"),
SchemaNode::scalar("attribute_class", "kill_eater_score_type_2"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("effect_type", "positive"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("495", vec![SchemaNode::scalar("name", "kill eater score type 3"),
SchemaNode::scalar("attribute_class", "kill_eater_score_type_3"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("effect_type", "positive"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("724", vec![SchemaNode::scalar("name", "weapon_stattrak_module_scale"),
SchemaNode::scalar("attribute_class", "weapon_stattrak_module_scale"),
SchemaNode::scalar("description_format", "value_is_percentage"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("783", vec![SchemaNode::scalar("name", "extinguish restores health"),
SchemaNode::scalar("attribute_class", "extinguish_restores_health"),
SchemaNode::scalar("description_string", "#Attrib_ExtinguishRestoresHealth"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "0"),
SchemaNode::scalar("effect_type", "positive")]),
SchemaNode::object("796", vec![SchemaNode::scalar("name", "min_viewmodel_offset"),
SchemaNode::scalar("attribute_class", "min_viewmodel_offset"),
SchemaNode::scalar("attribute_type", "string"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1")]),
SchemaNode::object("839", vec![SchemaNode::scalar("name", "flame_spread_degree"),
SchemaNode::scalar("attribute_class", "flame_spread_degree"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("effect_type", "positive"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("841", vec![SchemaNode::scalar("name", "flame_gravity"),
SchemaNode::scalar("attribute_class", "flame_gravity"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("843", vec![SchemaNode::scalar("name", "flame_drag"),
SchemaNode::scalar("attribute_class", "flame_drag"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("844", vec![SchemaNode::scalar("name", "flame_speed"),
SchemaNode::scalar("attribute_class", "flame_speed"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("862", vec![SchemaNode::scalar("name", "flame_lifetime"),
SchemaNode::scalar("attribute_class", "flame_lifetime"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("863", vec![SchemaNode::scalar("name", "flame_random_life_time_offset"),
SchemaNode::scalar("attribute_class", "flame_random_life_time_offset"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")]),
SchemaNode::object("865", vec![SchemaNode::scalar("name", "flame_up_speed"),
SchemaNode::scalar("attribute_class", "flame_up_speed"),
SchemaNode::scalar("description_format", "value_is_additive"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("stored_as_integer", "0")])],
items: vec![SchemaNode::object("default", vec![SchemaNode::scalar("name", "default"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("item_class", "tf_wearable"),
SchemaNode::scalar("item_name", "#TF_Default_ItemDef"),
SchemaNode::scalar("item_slot", "melee"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1")]),
SchemaNode::object("0", vec![SchemaNode::scalar("name", "TF_WEAPON_BAT"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_bat"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("1", vec![SchemaNode::scalar("name", "TF_WEAPON_BOTTLE"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_bottle"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("2", vec![SchemaNode::scalar("name", "TF_WEAPON_FIREAXE"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_fireaxe"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("3", vec![SchemaNode::scalar("name", "TF_WEAPON_CLUB"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_club"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("4", vec![SchemaNode::scalar("name", "TF_WEAPON_KNIFE"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_knife"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("5", vec![SchemaNode::scalar("name", "TF_WEAPON_FISTS"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_fists"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("6", vec![SchemaNode::scalar("name", "TF_WEAPON_SHOVEL"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_shovel"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("7", vec![SchemaNode::scalar("name", "TF_WEAPON_WRENCH"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_wrench"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("8", vec![SchemaNode::scalar("name", "TF_WEAPON_BONESAW"),
SchemaNode::scalar("prefab", "weapon_bonesaw"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1")]),
SchemaNode::object("9", vec![SchemaNode::scalar("name", "TF_WEAPON_SHOTGUN_PRIMARY"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_shotgun"),
SchemaNode::scalar("item_slot", "primary"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1")]),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("10", vec![SchemaNode::scalar("name", "TF_WEAPON_SHOTGUN_SOLDIER"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_shotgun"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("soldier", "1")]),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("11", vec![SchemaNode::scalar("name", "TF_WEAPON_SHOTGUN_HWG"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_shotgun"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("heavy", "1")]),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("12", vec![SchemaNode::scalar("name", "TF_WEAPON_SHOTGUN_PYRO"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_shotgun"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("pyro", "1")]),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("13", vec![SchemaNode::scalar("name", "TF_WEAPON_SCATTERGUN"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_scattergun"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("14", vec![SchemaNode::scalar("name", "TF_WEAPON_SNIPERRIFLE"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_sniperrifle"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("15", vec![SchemaNode::scalar("name", "TF_WEAPON_MINIGUN"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_minigun"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("16", vec![SchemaNode::scalar("name", "TF_WEAPON_SMG"),
SchemaNode::scalar("prefab", "weapon_smg"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_smg"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_SMG"),
SchemaNode::scalar("item_name", "#TF_Weapon_SMG"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_smg"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_smg/c_smg.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("sniper", "1")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav")]),
SchemaNode::object("17", vec![SchemaNode::scalar("name", "TF_WEAPON_SYRINGEGUN_MEDIC"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_syringegun"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("18", vec![SchemaNode::scalar("name", "TF_WEAPON_ROCKETLAUNCHER"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_rocketlauncher"),
SchemaNode::scalar("xifier_class_remap", "rocket_launcher"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("19", vec![SchemaNode::scalar("name", "TF_WEAPON_GRENADELAUNCHER"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_grenade_launcher"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("20", vec![SchemaNode::scalar("name", "TF_WEAPON_PIPEBOMBLAUNCHER"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_stickybomb_launcher"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("21", vec![SchemaNode::scalar("name", "TF_WEAPON_FLAMETHROWER"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_flamethrower"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::object("visuals", vec![SchemaNode::object("attached_models", vec![SchemaNode::object("0", vec![SchemaNode::scalar("model", "models/weapons/c_models/c_flamethrower/c_flamethrower_pilotlight.mdl")])])])]),
SchemaNode::object("22", vec![SchemaNode::scalar("name", "TF_WEAPON_PISTOL"),
SchemaNode::scalar("prefab", "weapon_pistol"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_pistol"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Pistol"),
SchemaNode::scalar("item_name", "#TF_Weapon_Pistol"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_pistol"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_pistol/c_pistol.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav")]),
SchemaNode::object("23", vec![SchemaNode::scalar("name", "TF_WEAPON_PISTOL_SCOUT"),
SchemaNode::scalar("prefab", "weapon_pistol"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_pistol"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Pistol"),
SchemaNode::scalar("item_name", "#TF_Weapon_Pistol"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/c_models/c_pistol"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_pistol/c_pistol.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("scout", "1")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav")]),
SchemaNode::object("24", vec![SchemaNode::scalar("name", "TF_WEAPON_REVOLVER"),
SchemaNode::scalar("prefab", "weapon_revolver"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::object("tags", vec![SchemaNode::scalar("can_deal_damage", "1"),
SchemaNode::scalar("can_deal_mvm_penetration_damage", "1"),
SchemaNode::scalar("can_deal_long_distance_damage", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_revolver"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Revolver"),
SchemaNode::scalar("item_name", "#TF_Weapon_Revolver"),
SchemaNode::scalar("item_slot", "secondary"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_revolver"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_revolver/c_revolver.mdl"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("spy", "1")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_light_gun_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_light_gun_drop.wav")]),
SchemaNode::object("25", vec![SchemaNode::scalar("name", "TF_WEAPON_PDA_ENGINEER_BUILD"),
SchemaNode::object("capabilities", vec![SchemaNode::scalar("nameable", "1")]),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_pda_engineer_build"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_name", "#TF_Weapon_PDA_Engineer_Builder"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_PDA_Engineer"),
SchemaNode::scalar("item_slot", "pda"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_builder"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_builder/c_builder.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::object("attributes", vec![SchemaNode::object("kill eater score type", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type"),
SchemaNode::scalar("value", "3")]),
SchemaNode::object("kill eater score type 2", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type_2"),
SchemaNode::scalar("value", "59")]),
SchemaNode::object("kill eater score type 3", vec![SchemaNode::scalar("attribute_class", "kill_eater_score_type_3"),
SchemaNode::scalar("value", "60")])]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav"),
SchemaNode::object("visuals", vec![SchemaNode::object("animation_replacement", vec![SchemaNode::scalar("ACT_VM_IDLE", "ACT_ENGINEER_PDA2_VM_IDLE"),
SchemaNode::scalar("ACT_VM_DRAW", "ACT_ENGINEER_PDA2_VM_DRAW")])])]),
SchemaNode::object("26", vec![SchemaNode::scalar("name", "TF_WEAPON_PDA_ENGINEER_DESTROY"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_pda_engineer_destroy"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_name", "#TF_Weapon_PDA_Engineer_Destroyer"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_PDA_Engineer"),
SchemaNode::scalar("item_slot", "pda2"),
SchemaNode::scalar("anim_slot", "pda"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_pda_engineer"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_pda_engineer/c_pda_engineer.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -10")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav"),
SchemaNode::object("visuals", vec![SchemaNode::object("animation_replacement", vec![SchemaNode::scalar("ACT_VM_IDLE", "ACT_ENGINEER_PDA1_VM_IDLE"),
SchemaNode::scalar("ACT_VM_DRAW", "ACT_ENGINEER_PDA1_VM_DRAW")])])]),
SchemaNode::object("27", vec![SchemaNode::scalar("name", "TF_WEAPON_PDA_SPY"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_pda_spy"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_name", "#TF_Weapon_Disguise_Kit"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_Disguise_Kit_Type"),
SchemaNode::scalar("item_slot", "pda"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_cigarette_case"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("model_player", "models/weapons/w_models/w_cigarette_case.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("spy", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -6")])]),
SchemaNode::object("28", vec![SchemaNode::scalar("name", "TF_WEAPON_BUILDER"),
SchemaNode::scalar("hidden", "1"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("item_class", "tf_weapon_builder"),
SchemaNode::scalar("craft_class", "weapon"),
SchemaNode::scalar("craft_material_type", "weapon"),
SchemaNode::scalar("item_type_name", "#TF_Weapon_PDA_Engineer"),
SchemaNode::scalar("item_name", "#TF_Weapon_PDA_Engineer"),
SchemaNode::scalar("item_slot", "building"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1"),
SchemaNode::scalar("min_ilevel", "1"),
SchemaNode::scalar("max_ilevel", "1"),
SchemaNode::scalar("image_inventory", "backpack/weapons/w_models/w_pda_engineer"),
SchemaNode::scalar("image_inventory_size_w", "128"),
SchemaNode::scalar("image_inventory_size_h", "82"),
SchemaNode::scalar("attach_to_hands", "1"),
SchemaNode::scalar("model_player", "models/weapons/c_models/c_toolbox/c_toolbox.mdl"),
SchemaNode::object("used_by_classes", vec![SchemaNode::scalar("engineer", "1")]),
SchemaNode::object("static_attrs", vec![SchemaNode::scalar("min_viewmodel_offset", "10 0 -8")]),
SchemaNode::scalar("mouse_pressed_sound", "ui/item_metal_weapon_pickup.wav"),
SchemaNode::scalar("drop_sound", "ui/item_metal_weapon_drop.wav"),
SchemaNode::object("visuals", vec![SchemaNode::object("animation_replacement", vec![SchemaNode::scalar("ACT_VM_IDLE", "ACT_ENGINEER_BLD_VM_IDLE"),
SchemaNode::scalar("ACT_VM_DRAW", "ACT_ENGINEER_BLD_VM_DRAW")])])]),
SchemaNode::object("29", vec![SchemaNode::scalar("name", "TF_WEAPON_MEDIGUN"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_medigun"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("30", vec![SchemaNode::scalar("name", "TF_WEAPON_INVIS"),
SchemaNode::scalar("first_sale_date", "2010/09/29"),
SchemaNode::scalar("prefab", "weapon_invis"),
SchemaNode::scalar("baseitem", "1")]),
SchemaNode::object("735", vec![SchemaNode::scalar("name", "TF_WEAPON_BUILDER_SPY"),
SchemaNode::scalar("prefab", "weapon_sapper"),
SchemaNode::scalar("item_quality", "normal"),
SchemaNode::scalar("baseitem", "1")])],
}
}
