// Generated from the configured item schema and sound manifest.
pub const MISSING_CONFIGURED_SOUNDS: &[&str] = &[];
pub const CONFIGURED_SOUNDS: &[(&str, &str, u8)] = &[
("BostonBasher.HitWorld", "scripts/game_sounds_weapons.txt", 2),
("BostonBasher.Impact", "scripts/game_sounds_weapons.txt", 4),
("TFPlayer.CritHit", "scripts/game_sounds_player.txt", 5),
("TFPlayer.CritHitMini", "scripts/game_sounds_player.txt", 5),
("Weapon_Ambassador.Single", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Ambassador.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_BackShot_Shotty.Single", "scripts/game_sounds_weapons.txt", 1),
("Weapon_BackShot_Shotty.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Back_Scatter.Single", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Back_Scatter.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Bat.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Bazaar_Bargain.Single", "scripts/game_sounds_weapons.txt", 5),
("Weapon_Bazaar_Bargain.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_BoneSaw.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Bottle.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_BoxingGloves.HitFlesh", "scripts/game_sounds_weapons.txt", 4),
("Weapon_BoxingGloves.HitWorld", "scripts/game_sounds_weapons.txt", 2),
("Weapon_BoxingGloves.Miss", "scripts/game_sounds_weapons.txt", 3),
("Weapon_BoxingGloves.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Enforcer.Single", "scripts/game_sounds_weapons.txt", 6),
("Weapon_Enforcer.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_FamilyBusiness.Single", "scripts/game_sounds_weapons.txt", 1),
("Weapon_FamilyBusiness.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_FireAxe.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Fist.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.ClipEmpty", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.Fire", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.FireCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.Reload", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.Spin", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.WindDown", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Gatling.WindUp", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Hands.Push", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Hands.PushImpact", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Machete.HitFlesh", "scripts/game_sounds_weapons.txt", 3),
("Weapon_Machete.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Marked_for_Death.Indicator", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Marked_for_Death.Initial", "scripts/game_sounds_weapons.txt", 3),
("Weapon_Minifun.ClipEmpty", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Minifun.Fire", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Minifun.FireCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Minifun.Reload", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Minifun.Spin", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Minifun.WindDown", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Minifun.WindUp", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Reserve_Shooter.Single", "scripts/game_sounds_weapons.txt", 4),
("Weapon_Reserve_Shooter.SingleCrit", "scripts/game_sounds_weapons.txt", 4),
("Weapon_Scatter_Gun_Double.Single", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Scatter_Gun_Double.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Short_Stop.Reload", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Short_Stop.Single", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Short_Stop.SingleCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Shovel.MissCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Tomislav.Fire", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Tomislav.FireCrit", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Tomislav.WindDown", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Tomislav.WindUp", "scripts/game_sounds_weapons.txt", 1),
("Weapon_Wrench.MissCrit", "scripts/game_sounds_weapons.txt", 1),
];
pub const MELEE_CRITICAL_SOUNDS: &[(u32, u8)] = &[
(0, 10),
(1, 14),
(2, 23),
(3, 35),
(5, 24),
(6, 52),
(7, 57),
(8, 13),
(155, 57),
(171, 35),
(214, 23),
(232, 35),
(310, 18),
(325, 10),
(326, 23),
(355, 10),
(401, 35),
(416, 52),
];
